title: Backbone Knowledgebase
lang: en
description: Documentation and Information for Backbone Cabal

repository: backbonecabal/knowledgebase

permalink: /:title/

## local method ##
# theme: jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - LICENSE

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using Google Analytics
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-sitemap
